FROM arm32v7/node:14 AS builder
WORKDIR /app
COPY . ./
WORKDIR /app/branch
ARG NPM_AUTH_TOKEN
ENV NPM_AUTH_TOKEN ${NPM_AUTH_TOKEN}
RUN npm install
RUN npm run cp:shared
RUN npm run build

FROM arm32v7/node:14 AS starter
WORKDIR /app
COPY --from=builder /app/branch/dist ./dist
RUN npm install -g http-server
CMD [ "http-server", "./dist", "-p", "5001" ]