FROM arm32v7/node:14 AS builder
WORKDIR /app
COPY . ./
WORKDIR /app/branch
RUN --mount=type=secret,id=NPM_AUTH_TOKEN cat /run/secrets/NPM_AUTH_TOKEN npm install
RUN npm run cp:shared
RUN npm run build

FROM arm32v7/node:14 AS starter
WORKDIR /app
COPY --from=builder /app/branch/dist ./dist
RUN npm install -g http-server
CMD [ "http-server", "./dist", "-p", "5001" ]