name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v2
      - name: 🏠 Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: ⚙️ Install dependencies
        run: npm ci
      - name: 🔬 Lint
        run: npm run lint
      - name: 🔬 Format
        run: npm run prettier
      - name: 🔬 Type checking
        run: npm run typecheck
      - name: 🧪 Test
        run: npm run test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v2
      - name: 🏠 Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: ⚙️ Install dependencies
        run: npm ci
      - name: 👷🏽‍♂️ Build package
        run: npm run build
      - name: 🚀 Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}